# Generated by Django 4.2 on 2023-04-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
    ]
