# Generated by Django 4.2 on 2023-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_balance_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
